/**
 * Single source of truth for the playground presets.
 *
 * Each preset becomes its OWN crawlable page (demos/<slug>.html) plus a card on
 * the hub (demos/index.html), generated by scripts/build-demo-pages.js. Editing a
 * demo? Edit it here and re-run `npm run build:demo-pages`.
 *
 * SEO fields per preset: slug, seoTitle, seoDescription (≤160 chars), intro (a
 * short unique paragraph shown above the playground). `desc` is the one-line
 * playground caption; `badge` is the size/label pill; `code` is the live snippet.
 */
export const CDN = 'https://cdn.jsdelivr.net/npm/@oix1987/yjd';
export const SITE = 'https://yjd.io';

export const PRESETS = [
  {
    slug: 'minimal', id: 'minimal', title: 'Minimal', badge: '~17 KB JS',
    desc: 'Comment / chat box — bold, italic, underline, link.',
    seoTitle: 'Minimal rich text editor demo — a 17 KB comment box',
    seoDescription:
      'A live 17 KB rich text editor demo: bold, italic, underline and links — the tree-shakeable build for comment boxes and chat inputs. Edit the config and run it.',
    intro:
      'The smallest useful build — bold, italic, underline and a link, and nothing else. Import only those formats from the tree-shakeable <code>/core</code> entry and ship about <strong>17 KB of JavaScript</strong>. Ideal for comment boxes, review fields and chat inputs where a full toolbar would be overkill.',
    code:
`// 1) Add the stylesheet once:
//    <link rel="stylesheet" href="${CDN}/lib/styles.min.css">

// 2) Import only what you need (tree-shaken):
import { Editor, registry, Bold, Italic, Underline, Link, Toolbar, History }
  from '${CDN}/core.js';

registry.register('formats/bold', Bold);
registry.register('formats/italic', Italic);
registry.register('formats/underline', Underline);
registry.register('formats/link', Link);
registry.register('modules/toolbar', Toolbar);
registry.register('modules/history', History);

new Editor('#editor', {
  width: '100%',
  placeholder: 'Write a comment…',
  content: '<p>🔥 This thread is gold! Loved the <b>breakdown on retention</b> — bookmarking it. <a href="https://example.com">Full notes here</a> 👏 <span style="color: #6d5efc">#growth</span> <span style="color: #6d5efc">#startups</span></p>',
  toolbar1: [
    { group: 'text-format', items: ['bold', 'italic', 'underline'] },
    { group: 'link', items: ['link'] }
  ],
  formats: ['bold', 'italic', 'underline', 'link'],
  modules: ['toolbar', 'history']
});`
  },
  {
    slug: 'bubble', id: 'bubble', title: 'Bubble', badge: '~23 KB JS',
    desc: 'No top toolbar — select text for the floating bar; type / for blocks.',
    seoTitle: 'Bubble menu rich text editor demo — floating toolbar on select',
    seoDescription:
      'A live bubble-menu editor demo: no top toolbar — select text for a floating format bar, type “/” for blocks. The distraction-free, tree-shakeable build (~23 KB).',
    intro:
      'A distraction-free writing surface with <strong>no top toolbar</strong>. Select any text and a floating “bubble” bar appears with the formatting you need; type <code>/</code> for a block menu (headings, lists, and more). Great for Medium- or Notion-style editors where chrome should stay out of the way.',
    code:
`// Stylesheet: <link rel="stylesheet" href="${CDN}/lib/styles.min.css">
import { Editor, registry, Bold, Italic, Underline, Strike, Heading, List,
  FontFamily, History, BlockToolbar, SlashMenu } from '${CDN}/core.js';

registry.register('formats/bold', Bold);
registry.register('formats/italic', Italic);
registry.register('formats/underline', Underline);
registry.register('formats/strike', Strike);
registry.register('formats/heading', Heading);
registry.register('formats/list', List);
registry.register('formats/font-family', FontFamily);
registry.register('modules/history', History);
registry.register('modules/block-toolbar', BlockToolbar);
registry.register('modules/slash-menu', SlashMenu);

new Editor('#editor', {
  width: '100%',
  content: '<h3>✨ Shipping update</h3><p>We just launched <b>dark mode</b> 🌙 — way smoother than the beta. <i>Highlight any text</i> to format it 💬</p><ul><li>⚡ Faster load</li><li>🎨 New themes</li><li>♿ Better contrast</li></ul><p><span style="color: #6d5efc">#release</span> <span style="color: #6d5efc">#darkmode</span> <span style="color: #6d5efc">#buildinpublic</span></p>',
  // No 'toolbar' module → no top toolbar.
  modules: ['history', 'block-toolbar', 'slash-menu'],
  formats: ['bold', 'italic', 'underline', 'strike', 'heading', 'list', 'font-family'],
  // Which tools appear in the floating bubble bar:
  'block-toolbar': { buttons: ['bold', 'italic', 'underline', 'link', 'code'] },
  features: { wordCount: false, breadcrumb: false }
});`
  },
  {
    slug: 'prompt', id: 'prompt', title: 'Prompt', badge: 'chat input',
    desc: 'Mobile-first chat pill — "+" adds an image, basic tools, a send button. Enter sends.',
    seoTitle: 'AI chat input demo — a prompt-style rich text composer',
    seoDescription:
      'A live prompt/chat composer demo: a mobile-first rounded pill with a “+” for images, basic formatting, attachments and a send button. Enter sends, Shift+Enter newlines.',
    intro:
      'A chat-style composer in the shape of a rounded pill — the same layout as modern AI prompt inputs. The “+” adds an image (a popover of image/file/video on desktop), attachments ride along as removable thumbnails, and <strong>Enter sends</strong> while the on-screen keyboard’s return key inserts a newline on mobile. Built for AI prompts, messaging and comment composers.',
    code:
`// Stylesheet: <link rel="stylesheet" href="${CDN}/lib/styles.min.css">
import { Editor, registry, applyEditorInput, Bold, Italic, Image,
  Toolbar, History } from '${CDN}/core.js';

registry.register('formats/bold', Bold);
registry.register('formats/italic', Italic);
registry.register('formats/image', Image);
registry.register('modules/toolbar', Toolbar);
registry.register('modules/history', History);

// Enables file-upload insertion (image/file) on a /core build.
applyEditorInput(Editor);

new Editor('#editor', {
  width: '100%',
  layout: 'prompt',                        // chat pill + bottom action bar
  placeholder: 'Message yjd…',
  content: '<p>Viết lại đoạn này ngắn gọn hơn 👋</p>',
  prompt: {
    add: ['image', 'file', 'video'],       // mobile: "+" adds image · desktop: menu
    tools: ['bold', 'italic'],             // basic tools, no popovers
  },
  // Attachments show as removable thumbnails and travel with the message.
  submit: { onSubmit: (html, ed) => console.log('send:', html, ed.getAttachments()) },
});`
  },
  {
    slug: 'basic', id: 'basic', title: 'Basic', badge: '~28 KB JS',
    desc: 'Blog / notes — try typing / for the command menu.',
    seoTitle: 'Basic rich text editor demo — blog & notes with a slash menu',
    seoDescription:
      'A live blog/notes editor demo: headings, lists, alignment and a “/” command menu in a ~28 KB tree-shakeable build. Edit the config and run it in your browser.',
    intro:
      'A comfortable everyday editor for <strong>blogs and notes</strong>: headings, lists, alignment, strike-through and links, plus a <code>/</code> command menu and the floating bubble bar. Around <strong>28 KB</strong> — a balanced middle ground between the minimal comment box and the full CMS build.',
    code:
`// Stylesheet: <link rel="stylesheet" href="${CDN}/lib/styles.min.css">
import { Editor, registry, Bold, Italic, Underline, Strike, Link, Heading, List,
  TextAlign, FontFamily, Toolbar, History, SlashMenu, BlockToolbar } from '${CDN}/core.js';

registry.register('formats/bold', Bold);
registry.register('formats/italic', Italic);
registry.register('formats/underline', Underline);
registry.register('formats/strike', Strike);
registry.register('formats/link', Link);
registry.register('formats/heading', Heading);
registry.register('formats/list', List);
registry.register('formats/text-align', TextAlign);
registry.register('formats/font-family', FontFamily);
registry.register('modules/toolbar', Toolbar);
registry.register('modules/history', History);
registry.register('modules/slash-menu', SlashMenu);
registry.register('modules/block-toolbar', BlockToolbar);

new Editor('#editor', {
  width: '100%',
  content: '<h2>🍞 Weekend baking win</h2><p>The sourdough finally worked — <b>crispy crust</b>, <i>open crumb</i>, <s>no more bricks</s> 🙌</p><p>My tweaks 👇</p><ul><li>🧊 Overnight cold proof</li><li>🔥 Hotter oven + steam</li></ul><ol><li>Mix &amp; rest</li><li>Stretch &amp; fold ×4</li><li>Shape &amp; chill</li></ol><p style="text-align: center">📍 <span style="color: #6d5efc">#sourdough</span> <span style="color: #6d5efc">#homebaking</span> <span style="color: #6d5efc">#foodie</span></p>',
  placeholder: 'Write your post…',
  toolbar1: [
    { group: 'text-format', items: ['bold', 'italic', 'underline', 'strike'] },
    { group: 'paragraph', items: ['heading'] },
    { group: 'link', items: ['link'] },
    { group: 'paragraph-ops', items: ['list', 'text-align'] },
    { group: 'history', items: ['undo', 'redo'] }
  ],
  formats: ['bold', 'italic', 'underline', 'strike', 'heading', 'list', 'text-align', 'font-family', 'link'],
  modules: ['toolbar', 'history', 'slash-menu', 'block-toolbar']
});`
  },
  {
    slug: 'standard', id: 'standard', title: 'Standard', badge: '~46 KB JS',
    desc: 'CMS / docs — colour, image, table, find & replace, code view.',
    seoTitle: 'Full-featured rich text editor demo — CMS & docs (tables, images)',
    seoDescription:
      'A live CMS/docs editor demo: colour, images, tables, find & replace, indentation and a code view in a ~46 KB tree-shakeable build. Try it in your browser.',
    intro:
      'The <strong>CMS and documents</strong> build: text colour and highlight, images with drag-to-resize, tables, find &amp; replace, indentation, font sizing and an HTML code view — around <strong>46 KB</strong>. Everything a content editor needs without pulling the entire all-in-one bundle.',
    code:
`// Stylesheet: <link rel="stylesheet" href="${CDN}/lib/styles.min.css">
import { Editor, registry, Bold, Italic, Underline, Strike, Link, Heading, List,
  TextAlign, FontFamily, Color, Background, Image, Table, IndentIncrease,
  IndentDecrease, TextSize, Toolbar, History, SlashMenu, BlockToolbar,
  TableToolbar, FindReplace, CodeView, ResizeHandles } from '${CDN}/core.js';

[
  ['formats/bold', Bold], ['formats/italic', Italic], ['formats/underline', Underline],
  ['formats/strike', Strike], ['formats/link', Link], ['formats/heading', Heading],
  ['formats/list', List], ['formats/text-align', TextAlign], ['formats/font-family', FontFamily],
  ['formats/color', Color], ['formats/background', Background], ['formats/image', Image],
  ['formats/table', Table], ['formats/text-size', TextSize],
  ['formats/indent-increase', IndentIncrease], ['formats/indent-decrease', IndentDecrease],
  ['modules/toolbar', Toolbar], ['modules/history', History], ['modules/slash-menu', SlashMenu],
  ['modules/block-toolbar', BlockToolbar], ['modules/table-toolbar', TableToolbar],
  ['modules/find-replace', FindReplace], ['modules/code-view', CodeView],
  ['modules/resize-handles', ResizeHandles]
].forEach(([k, v]) => registry.register(k, v));

new Editor('#editor', {
  width: '100%',
  content: '<h1>🚀 Q3 product update</h1><p>Big quarter, team! <span style="color: #6d5efc"><b>3 new features</b></span> shipped, plus a few <span style="background-color: #fff3bf">things to watch</span> 👀</p><img class="inserted-image" src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&amp;q=80" alt="Dashboard screenshot" style="max-width: 100%; height: auto; border-radius: 8px"><p>Shoutout to <span style="color: #1c7ed6">@design</span> &amp; <span style="color: #1c7ed6">@mobile</span> 💜</p><h2>📊 Release summary</h2><table class="rich-editor-table"><tbody><tr><td><b>Area</b></td><td><b>Status</b></td></tr><tr><td>Editor</td><td>🟢 <span style="color: #2f9e44">Shipped</span></td></tr><tr><td>Mobile apps</td><td>🟠 <span style="color: #e8590c">In progress</span></td></tr><tr><td>Search</td><td>🔵 <span style="color: #1c7ed6">Planned</span></td></tr></tbody></table><p>Full notes in the <a href="https://example.com/changelog">changelog</a> · <span style="color: #6d5efc">#productupdate</span> <span style="color: #6d5efc">#shipit</span></p>',
  toolbar1: [
    { group: 'text-format', items: ['bold', 'italic', 'underline', 'strike'] },
    { group: 'paragraph', items: ['heading'] },
    { group: 'colors', items: ['color', 'background'] },
    { group: 'link', items: ['link'] },
    { group: 'paragraph-ops', items: ['list', 'indent-increase', 'indent-decrease', 'text-align'] },
    { group: 'insert', items: ['image', 'table'] },
    { group: 'font', items: ['text-size'] },
    { group: 'tools', items: ['find', 'code-view'] },
    { group: 'history', items: ['undo', 'redo'] }
  ],
  formats: ['bold', 'italic', 'underline', 'strike', 'color', 'background', 'heading',
    'text-size', 'text-align', 'list', 'indent-increase', 'indent-decrease', 'link', 'image', 'table'],
  modules: ['toolbar', 'history', 'slash-menu', 'block-toolbar', 'table-toolbar',
    'find-replace', 'code-view', 'resize-handles']
});`
  },
  {
    slug: 'social', id: 'social', title: 'Social', badge: 'image + video',
    desc: 'A creator post with a photo and an embedded video, drag-to-resize media, colours, mentions and hashtags.',
    seoTitle: 'Social post editor demo — images, video embeds, mentions & hashtags',
    seoDescription:
      'A live social/creator post editor demo: photos, embedded video, drag-to-resize media, colours, emoji, @mentions and #hashtags — a tree-shakeable build you can try now.',
    intro:
      'A <strong>creator post</strong> composer: inline photos and embedded video with drag-to-resize, colour and highlight, emoji, and @mentions and #hashtags. The build for social feeds, community posts and anywhere rich media travels inside the text.',
    code:
`// Stylesheet: <link rel="stylesheet" href="${CDN}/lib/styles.min.css">
import { Editor, registry, Bold, Italic, Underline, Strike, Link, Heading, List,
  TextAlign, Color, Background, Image, Video, Emoji, Toolbar, History, SlashMenu,
  BlockToolbar, ResizeHandles } from '${CDN}/core.js';

[
  ['formats/bold', Bold], ['formats/italic', Italic], ['formats/underline', Underline],
  ['formats/strike', Strike], ['formats/link', Link], ['formats/heading', Heading],
  ['formats/list', List], ['formats/text-align', TextAlign], ['formats/color', Color],
  ['formats/background', Background], ['formats/image', Image], ['formats/video', Video],
  ['formats/emoji', Emoji],
  ['modules/toolbar', Toolbar], ['modules/history', History], ['modules/slash-menu', SlashMenu],
  ['modules/block-toolbar', BlockToolbar], ['modules/resize-handles', ResizeHandles]
].forEach(([k, v]) => registry.register(k, v));

new Editor('#editor', {
  width: '100%',
  content:
    '<h2>🌅 48 hours in Da Lat</h2>' +
    '<p>Best long weekend this year — <b>pine forests</b>, <i>cold brew</i>, ' +
    'and endless <span style="color: #6d5efc">#views</span> 📸</p>' +
    '<img class="inserted-image" src="https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&q=80" ' +
    'alt="Misty pine hills" style="max-width: 100%; height: auto; border-radius: 10px">' +
    '<p>🎬 Watch the 60-second recap:</p>' +
    '<iframe class="inserted-video youtube-video" src="https://www.youtube.com/embed/ScMzIvxBSi4" ' +
    'width="560" height="315" style="max-width: 100%; border-radius: 10px" frameborder="0" allowfullscreen></iframe>' +
    '<p>Shoutout to <span style="color: #1c7ed6">@travelcrew</span> 💚 ' +
    '<span style="color: #6d5efc">#dalat</span> <span style="color: #6d5efc">#vietnam</span> ' +
    '<span style="color: #6d5efc">#travel</span></p>',
  toolbar1: [
    { group: 'text-format', items: ['bold', 'italic', 'underline', 'strike'] },
    { group: 'paragraph', items: ['heading'] },
    { group: 'colors', items: ['color', 'background'] },
    { group: 'link', items: ['link'] },
    { group: 'paragraph-ops', items: ['list', 'text-align'] },
    { group: 'insert', items: ['image', 'video', 'emoji'] },
    { group: 'history', items: ['undo', 'redo'] }
  ],
  formats: ['bold', 'italic', 'underline', 'strike', 'color', 'background',
    'heading', 'text-align', 'list', 'link', 'image', 'video', 'emoji'],
  modules: ['toolbar', 'history', 'slash-menu', 'block-toolbar', 'resize-handles']
});`
  }
];
